version: '2'
services:

  train:
    links:
      - kafka
      - train-db
    image: train
    restart: always
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  train-db:
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: train
    image: mysql
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  timetable:
    links:
      - train
      - kafka
    image: timetable
    restart: always
    ports:
      - 8081:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    restart: always
    ports:
      - 9092:9092
    environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  zookeeper:
      image: wurstmeister/zookeeper
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "10"